apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-admin
data:
  APP_NAME: "Banking Admin Api"
  APP_ENV: "production"
  APP_DEBUG: "true"
  APP_URL: "https://api.admin.alpinebanking.software"
  LOG_LEVEL: "debug"
  DB_CONNECTION: "mysql"


---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: banking-admin-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: banking-admin-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-admin-api
  labels:
    app: banking-admin-api-deployment
  annotations:
    keel.sh/pollSchedule: "@every 10s"
    keel.sh/policy: force
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-admin-api
  template:
    metadata:
      labels:
        app: banking-admin-api
    spec:
      imagePullSecrets:
        - name: ghcrregistrypullsecret
      containers:
        - name: banking-app
          imagePullPolicy: Always
          image: ghcr.io/oryono/banking-admin:latest
          ports:
            - containerPort: 80
#          lifecycle:
#            postStart:
#              exec:
#                command: [ "/bin/bash", "./deploy.sh" ]
          env:
            - name: BANKING_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: banking-admin
                  key: BANKING_DATABASE_URL

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: banking-admin
                  key: DATABASE_URL

            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: banking-admin
                  key: APP_KEY

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: banking-admin
                  key: JWT_SECRET
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: banking-admin
                  key: APP_NAME

            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: banking-admin
                  key: APP_ENV

            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: banking-admin
                  key: APP_DEBUG

            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  name: banking-admin
                  key: APP_URL

            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: banking-admin
                  key: LOG_LEVEL

            - name: DB_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: banking-admin
                  key: DB_CONNECTION

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
  annotations:
    keel.sh/pollSchedule: "@every 10s"
    keel.sh/policy: force
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
      containers:
        - name: mysql
          imagePullPolicy: Always
          image: bitnami/mysql
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          env:
                - name: MYSQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: mysql
                      key: MYSQL_USER
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysql
                      key: MYSQL_PASSWORD

                - name: MYSQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: mysql
                      key: MYSQL_DATABASE

                - name: MYSQL_ROOT_PASSWORD
                  value: "root"

                - name: MYSQL_AUTHENTICATION_PLUGIN
                  value: "mysql_native_password"

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: banking-admin-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    -   hosts:
          - alpinebanking.software
        secretName: alpinebanking-software-secret
  rules:
    - host: "banking-admin-api.alpinebanking.software"
      http:
        paths:
          - backend:
              serviceName: banking-admin-api
              servicePort: 80

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
